[package]
name = "uamqp"
version = "0.1.0"
edition = "2021"
authors = ["Miroljub Tomic <miroljub1995@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
lapin = "2"
tokio = { version = "1.18.2", features = ["full"] }
